---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucasmadranges.
--- DateTime: 12/07/2024 18:55
---

local function randomNumber(valMax)
    return math.random(valMax)
end

local function separateLine()
    io.write("--------------------------------------------\n");
end

print("Bienvenue dans Guess My Number en Lua by Lucas Madranges !")
local gameStart = true

while gameStart do
    io.write("Choisis un nombre maximum : ")
    local maxValue = io.read("*n")
    separateLine()
    io.write("Le nombre que tu as choisi est : ", maxValue, "\n")
    io.read()
    io.write("Est-tu sur de vouloir continuer (yes/no) ? ")
    local choice = io.read()

    if choice == "yes" then
        separateLine()
        io.write("Le nombre sera compris entre 0 et ", maxValue, "\n")
        local random = randomNumber(maxValue)
        io.write("Que le jeu commence ! Est-tu prêt (yes/no) ? ")
        local choiceTwo = io.read()

        if choiceTwo == "yes" or choiceTwo == "no" then
            separateLine()
            io.write("Le jeu n'attend pas !\n")
            local numChoice
            local nbrCoup = 0

            while numChoice ~= random do
                io.write("Choisis un nombre : ")
                numChoice = io.read("*n")

                if numChoice > maxValue then
                    io.write("Le nombre à trouvé ne peut pas être supérieur au nombre aléatoire...\n")
                elseif random > numChoice then
                    io.write("C'est + !\n")
                    nbrCoup = nbrCoup + 1
                elseif random < numChoice then
                    io.write("C'est - !\n")
                    nbrCoup = nbrCoup + 1
                elseif random == numChoice then
                    io.write("C'est gagné !\n")
                end
            end

            io.write("Bravo ! Le nombre à trouver été ", random, "\n")
            io.write("Vous avez trouvé le nombre en ", nbrCoup, " coups !\n")
            io.read()
            io.write("Veux-tu rejouer (yes/no) ? ")
            local choiceThree = io.read()

            if choiceThree == "no" then
                io.write("Merci d'avoir joué !\n")
                gameStart = false
            end
        end
    end
end